### PR TITLE
update dynamic plugin name to mcg-ms-console

### PR DESCRIPTION
**Pull request by SanjalKatiyar**
Every dynamic plugin has an unique name. Name for this plugin will be `mcg-ms-console`.
Making such changes at all required places as this name will be used by operator as well while creating a ConsolePlugin CR.

### CODE REVIEW

**Comment by debjyoti-pandit** [comment]
Apart from the above point, everything looks good :+1:

**Comment by cloudbehl** [comment]
> Apart from the above point, everything looks good 👍

which point? 

@SanjalKatiyar Can you add a description and sign the PRs?

**Comment by SanjalKatiyar** [comment]
> Apart from the above point, everything looks good +1

yeah u need to update your PR once this is merged... 
since plugin name is changed, translation namespace will change as well...

**Comment by SanjalKatiyar** [comment]
> > Apart from the above point, everything looks good +1
> 
> which point?
> 
> @SanjalKatiyar Can you add a description and sign the PRs?

ack...

**Pull request merged**
